name: Build and Push Docker Image to AWS ECR
run-name: deploy-to-aws

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker login
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 650251712908.dkr.ecr.us-east-2.amazonaws.com
          
      - name: Build Docker image
        run: |
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GHA_TOKEN }} -t ${{ secrets.AWS_ECR_REPOSITORY }}/${{ github.sha }} .

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.AWS_ECR_REPOSITORY }}/${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest