name: Deploy-To-Azure
run-name: deploy-to-azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        run: |
          docker login ${{ secrets.CONTAINER_REGISTRY_URL }} -u ${{ secrets.CONTAINER_REGISTRY_NAME }} -p ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.CONTAINER_REGISTRY_NAME }}:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.CONTAINER_REGISTRY_NAME }}:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINER_REGISTRY_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name ${{ secrets.WEB_APP_FOR_CONTAINERS_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --docker-custom-image-name ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ secrets.CONTAINER_REGISTRY_NAME }}:${{ github.sha }} \
            --docker-registry-server-url https://${{ secrets.CONTAINER_REGISTRY_URL }}

      - name: Restart Azure Web App
        run: |
          az webapp restart --name ${{ secrets.WEB_APP_FOR_CONTAINERS_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}